"""Git operations — commit law versions with historical dates."""
from __future__ import annotations

import logging
import os
import subprocess
from datetime import date, datetime
from pathlib import Path

from .models import LawEntry, LawRevision

logger = logging.getLogger(__name__)


class GitCommitter:
    """Manages git commits for law versions."""

    def __init__(self, repo_path: str | Path):
        self.repo_path = Path(repo_path)
        self.author_name = "Fedlex Pipeline"
        self.author_email = "legalize-ch@openlegallab.ch"

    def _run_git(self, *args: str, env: dict | None = None) -> subprocess.CompletedProcess:
        merged_env = {**os.environ, **(env or {})}
        return subprocess.run(
            ["git", *args],
            cwd=self.repo_path,
            capture_output=True,
            text=True,
            env=merged_env,
        )

    def _date_env(self, d: date) -> dict:
        """Set GIT_AUTHOR_DATE and GIT_COMMITTER_DATE to a specific date."""
        # Git requires timezone offset in ISO 8601 format
        dt = datetime(d.year, d.month, d.day, 12, 0, 0)
        iso = dt.strftime("%Y-%m-%dT%H:%M:%S+01:00")
        return {
            "GIT_AUTHOR_DATE": iso,
            "GIT_COMMITTER_DATE": iso,
        }

    def init_repo(self):
        """Ensure the repo is initialized."""
        if not (self.repo_path / ".git").exists():
            self._run_git("init")
            self._run_git("checkout", "-b", "main")

    def commit_revision(self, revision: LawRevision, law: LawEntry | None = None) -> bool:
        """Write markdown files and commit with the revision date."""
        from .transformer import sr_to_path

        files_written = []
        for lang, markdown in revision.texts.items():
            rel_path = sr_to_path(revision.sr_number, lang)
            abs_path = self.repo_path / rel_path
            abs_path.parent.mkdir(parents=True, exist_ok=True)
            abs_path.write_text(markdown, encoding="utf-8")
            files_written.append(rel_path)

        if not files_written:
            return False

        # Stage files
        for f in files_written:
            self._run_git("add", f)

        # Check if there are actual changes
        status = self._run_git("diff", "--cached", "--quiet")
        if status.returncode == 0:
            logger.debug("No changes for SR %s @ %s, skipping", revision.sr_number, revision.date)
            return False

        # Build commit message
        title = revision.title_de or revision.title_fr or revision.title_it or f"SR {revision.sr_number}"
        msg = revision.message or f"SR {revision.sr_number}: {title} ({revision.date.isoformat()})"

        env = self._date_env(revision.date)
        env["GIT_AUTHOR_NAME"] = self.author_name
        env["GIT_AUTHOR_EMAIL"] = self.author_email
        env["GIT_COMMITTER_NAME"] = self.author_name
        env["GIT_COMMITTER_EMAIL"] = self.author_email

        result = self._run_git("commit", "-m", msg, env=env)
        if result.returncode != 0:
            logger.error("Commit failed: %s", result.stderr)
            return False

        logger.info("Committed: %s", msg)
        return True

    def commit_initial(self, message: str = "Initialize Swiss law repository"):
        """Create initial commit with repo metadata (only if README doesn't exist yet).

        Skips if README.md already exists to avoid overwriting a customized
        README on subsequent pipeline runs (fixes TD.2).
        """
        readme = self.repo_path / "README.md"
        if readme.exists():
            logger.debug("README.md already exists, skipping initial commit")
            return
        readme.write_text(
            "# Swiss Federal Law\n\n"
            "Version-controlled Swiss federal legislation in DE, FR, and IT.\n\n"
            "Each law is a Markdown file. Each revision is a commit.\n\n"
            "Data source: [Fedlex](https://fedlex.data.admin.ch)\n\n"
            "Generated by [legalize-ch](https://github.com/OpenLegalLab/swiss-law) "
            "inspired by [legalize.dev](https://legalize.dev)\n",
            encoding="utf-8",
        )
        self._run_git("add", "README.md")
        self._run_git("commit", "-m", message)
